### ISSUE TITLE
CG Failing to Load (Doesn't Actually Exist)

### ISSUE THREAD

**Issue by TheMSnap** [nunuhara/xsystem4#102]
I'm playing through the MG version of Rance VI using Alpha 3.2, and I've reached a point where a CG won't load and is causing the game to crash. I will attach the images of the event.
![8DC850A0-2DFA-4C82-BB1C-6F565A2853E8](https://user-images.githubusercontent.com/124742847/217399877-5d61b595-3752-403e-9aea-d036e90d6acd.jpg)
![IMG_0502](https://user-images.githubusercontent.com/124742847/217399907-59ba025b-a330-475c-b652-493d8df8fa62.jpg)
I've gone and checked the files themselves using the ALD Explorer and that CG doesn't seem to exist. I've also tried to insert a blank CG in its place, and that doesn't work either.

**Comment by nunuhara** [comment]
That's strange, even if it can't find a CG it shouldn't crash. I'm thinking the warning message is a symptom of a deeper problem, but looking at the code for that event I don't see anything out of the ordinary that would cause it to crash at that specific location.

Can you post your save data? Then I can try to reproduce and debug the issue on my end.
(Save data should be under `<game directory>\xsystem4\Rance6\SaveData`)

**Comment by TheMSnap** [comment]
[SaveData.zip](https://github.com/nunuhara/xsystem4/files/10680893/SaveData.zip)

Here you go. Thanks for taking the time to check this out.

**Comment by nunuhara** [comment]
This bug should be fixed in [alpha-3.3](https://github.com/nunuhara/xsystem4/releases/tag/alpha-3.3). I was able to play through that event with this version.

Thanks for reporting this.

**Comment by TheMSnap** [comment]
Thanks for fixing it! That was faster than I expected.
