### ISSUE TITLE
Text artifacts after `system.Reset()`

### ISSUE THREAD

**Issue by kichikuou** [nunuhara/xsystem4#113]
Steps to reproduce:

1. Run Rance 02
2. Select "Config" from the start menu
3. Select "Return to Title" -> "OK"
4. The opening movie restarts, but some text remains on the screen.

It looks like `CharSpriteManager` needs to be reset by `StoatSpriteEngine_ModuleFini`.

![Rance02-text-artifact](https://user-images.githubusercontent.com/12679772/231768623-75e67d08-f740-4872-9f67-e4b6d2d0a062.jpg)

**Comment by nunuhara** [comment]
Thanks. This and a few other reset issues should be fixed now.
