### ISSUE TITLE
Disappearing semi-transparent wall textures during movement

### ISSUE THREAD

**Issue by ripdog** [nunuhara/xsystem4#120]
Hi there, I've got another one for you :)

In the cave with all the portals where you need to find your party in Rance 6, Anise blasts some holes through which you can walk. When passing through one of these walls, the other holes disappear - becoming full wall-tile sized holes briefly during movement, but then becoming normal circular holes after I stop. This effect only happens when passing through one hole and looking at another, normal movement in open space doesn't cause it.

https://github.com/nunuhara/xsystem4/assets/174944/3f334077-7597-4154-be36-aec4789a6898

I think this is my save in this area, if you need one for repro. LMK if it's wrong, I cycle saves so I'll have this for a while.

Also, wow these compress well. 10% the size in plain old ZIP, less in 7z.

[SaveB.zip](https://github.com/nunuhara/xsystem4/files/11466220/SaveB.zip)

**Comment by kichikuou** [comment]
Thanks for the report, https://github.com/nunuhara/xsystem4/pull/121 should fix this.

**Comment by ripdog** [comment]
Awesome! Rance fans truly are the greatest. Gahahahaha!
