### ISSUE TITLE
[大番長 DL版] Saves made by XSystem4 can't be seen in System4 (Vice versa)

### ISSUE THREAD

**Issue by ck1521** [nunuhara/xsystem4#140]
Related Version: [XSystem4 Alpha-4.2](https://github.com/nunuhara/xsystem4/releases/tag/alpha-4.2)

大番長 DL is using  System 4.0 ver1.15 

Step to Reproduce:
1. Load 大番長 DL with XSystem4, Save game
2. Copy XSystem save files to the save folder of 大番長 DL
3. Start 大番長 DL, click load 
4. The load game list is empty, clicking empty rows (where the saves should be) doesn't work either
![ss](https://github.com/nunuhara/xsystem4/assets/10858385/7c2db98c-e42b-4c6e-8133-239a5e0ee8d5)

Vice versa (大番長 DL -> XSystem4)

Attached Save files from both System 4.0 ver1.15 and XSystem4
[大番長 DL.zip](https://github.com/nunuhara/xsystem4/files/13691113/DL.zip)

**Comment by kichikuou** [comment]
大番長*n*.asd is in gsave format which is compatible with System40.exe, but 大番長I*n*.asd, which is read and written by BanMisc HLL, is not in a compatible format.

I will make a patch.
