### ISSUE TITLE
MangaGamer's Beat Blades Haruka does not work

### ISSUE THREAD

**Issue by KaroNiko** [nunuhara/xsystem4#154]
Hi chief.
This game, tried on Android tablet, crashes at the title screen; then whatever choice you make gives the error as in the picture. The original Japanese version should work without problems, since it is mentioned in the compatibility list (超昂閃忍ハルカ, Chōkō Sennin Haruka)

![1710939408975](https://github.com/nunuhara/xsystem4/assets/163753361/e478624b-4e08-47c2-b66d-4b6f9ec87d06)

I quote what @Kichikuou wrote to me:
"SACTDX.Sound_GetGroupNum is not used in the Japanese version, so the problem seems to be specific to the MG version."

Can this be remedied?
Thank you for your attention and for your wonderful and invaluable work.

**Comment by KaroNiko** [comment]
Thanks @nunuhara  for responding and resolving the issue. I believe that kichikuou has not yet created the corresponding android apk from this version. As soon as it does, I will gladly test it on my tablet.

**Comment by KaroNiko** [comment]
As @nunuhara  has already pointed out, the text sometimes goes beyond the so-called speech bubble, only that the excess part is cut off, that is, it is not displayed on the screen. A backlog could have solved this problem, but unfortunately it is not present (I did not find it). There is the backscene option which, if selected, corrupts the font (the letters in each word result partially overlapped), which remains so until you close the application. @kichikuou , would it be possible to replace this font with another, or is it hard-coded? 
As for the videos, they don't seem to work in any of the titles I've tried; they just get skipped, and it's not much of a loss anyway.

![1722854658149](https://github.com/user-attachments/assets/09c5717d-2d15-4aa4-b48a-14491647d81e)

**Comment by kichikuou** [comment]
@nunuhara
That's very strange. I can't think of a reason.

@KaroNiko
Currently there's no way to change the font on Android, but two-finger swipe down will enter the backlog mode.

**Comment by KaroNiko** [comment]
Hey @nunuhara , two off-topic notes. 
I'll take this moment to tell you that I finished "Sengoku Rance -Three for the Slash! Thrust! Burn!- (EN)" on tablet some time ago without any problems, except for one: damn very short game! 🤣

In the compatibility list you should replace unknown with supported. Instead regarding "Dungeons and Dolls (EN)", have you not yet found a solution to make it compatible? If I remember correctly, it gave a similar error to B.B.Haruka's. Thanks for your attention.

**Comment by KaroNiko** [comment]
Hey @nunuhara , sorry to contact you here. In the compatibility list you didn't mention Beat Blades Haruka (MG version) yet: now it works perfectly, at least on Android device. It is better to mark it, to make it known to users. Greetings.
