### ISSUE TITLE
Window size and console

### ISSUE THREAD

**Issue by alan-zxs** [nunuhara/xsystem4#177]
Game: Rance VI + eng patch 2.05A
xsystem4 alpha-4.2
Windows 10
Everything is working fine. I just have a few small requests.

1. My laptop supports a maximum screen resolution of 1366x768.
The original engine changes the game window automatically, but xsystem4 does not.

[https://www.youtube.com/watch?v=z-FLshWA5us](https://www.youtube.com/watch?v=z-FLshWA5us)
And you can see that Alicesoft's launch video is missing, but that's minor.

2. Is there an option to hide the console when starting the game?
I've already tried to run it with --echo-message and --nodebug, but the cosnol is still running with the game.

3. Will the window menus be restored in future updates?
I mean, those things:

![menus](https://github.com/user-attachments/assets/4252aff1-b848-44e4-be76-e4e48223528a)

Thanks for the tool!

**Comment by nunuhara** [comment]
Items 1 and 2 should be fixed now in [the latest release](https://github.com/nunuhara/xsystem4/releases/tag/alpha-5). The console should only appear when running the 'xsystem4-debug.exe' executable.
As for 3, I don't have any plans to implement menu bars at the moment. It would be a nice feature, but it's tricky to do in a cross-platform way.
