### ISSUE TITLE
Z-ordering of PartsEngine

### ISSUE THREAD

**Issue by kichikuou** [nunuhara/xsystem4#180]
In Rance Quest, after the very first message, "閃きの迷宮" is highlighted on the map.
![System4](https://github.com/user-attachments/assets/f8e27827-e09c-4acb-b28b-2cb508232e36)

However, in xsystem4, the frame behind the text is not shown.
![xsystem4](https://github.com/user-attachments/assets/4c955bef-96e0-4ccf-a05f-a3c64ca221ae)

Looking at the scene info in xsys4dbg, the background is a normal sprite with Z=8001, the frame is in Parts with Z=8002, and the text is a normal sprite with Z=8004.

![background](https://github.com/user-attachments/assets/0f1dbfbe-0be8-47fc-8388-2b9fc2696e74)
![frame](https://github.com/user-attachments/assets/27636574-3ee8-4d71-90c3-f3b379a7c932)
![text](https://github.com/user-attachments/assets/2fa7c080-43fb-4641-9742-e0d28ef8d464)

Xsystem4 represents PartsEngine as a virtual sprite with Z=0, but this makes me think that the normal sprite and Parts should share one Z-space. @nunuhara have you seen any counter example?

**Comment by nunuhara** [comment]
If I remember correctly, I had tested the relative Z-ordering on the Shaman's Sanctuary .exe, and based my implementation on that.
However, I just ran that game in xsys4dbg and it looks similar to what you found in Rance Quest, with sprites and parts seeming to share one Z-space. So it might not be necessary to implement it that way I did, even if the .exe works that way.

**Comment by kichikuou** [comment]
In Shaman's Sanctuary .exe, by inserting the following code at the beginning of `０１／プロローグＡ()`, I was able to create a sprite whose Z-order is between two parts:

```
	int nSp = ChipmunkSpriteEngine.SP_GetUnuseNum(1);
	ChipmunkSpriteEngine.SP_Create(nSp, 600, 600, 255, 0, 0, 255);
	ChipmunkSpriteEngine.SP_SetPos(nSp, 100, 0);
	ChipmunkSpriteEngine.SP_SetZ(nSp, 300);  // between 201 (background) and 550 (message window)
```

![Mankuchu_exe](https://github.com/user-attachments/assets/b45cdc96-83e2-440b-a96a-5e8e25539e6f)
![parts1](https://github.com/user-attachments/assets/932136ee-3561-419f-85cb-c1f4ae3b3e61)
![parts2](https://github.com/user-attachments/assets/7a64957d-ed4f-4b0d-a2e3-cf85cb6f71fa)


So, it is probably the correct behavior for sprites and parts to share one Z-space.

**Comment by nunuhara** [comment]
This should be fixed now. Each parts object is now a separate entity in the scene.
I tried to implement this with as little source code changes as possible to avoid breaking anything, with the result that the whole UpdateComponent process is probably more convoluted than it needs to be. But it works.

There's another graphical bug in Quest, right after the first battle (see below) but I don't think that one is related to Z-order.
![Screenshot_20240914_102930](https://github.com/user-attachments/assets/064a1bc1-534a-4826-b7f3-3d435ad42b4d)

**Comment by kichikuou** [comment]
Thanks!

That graphical bug should be fixed by https://github.com/nunuhara/xsystem4/pull/183.
