### ISSUE TITLE
bugged cglm version pulled by meson

### ISSUE THREAD

**Issue by minirop** [nunuhara/xsystem4#50]
Hello.

Meson downloads version v0.8.2 from cglm, but this version has an error with `glmc_vec4_scale_as` definition:

https://github.com/recp/cglm/blob/04eaf9c535d586deacb56f6f7f6e088bda2bfdb0/include/cglm/call/vec4.h#L102

It should be `vec4` instead of `vec3`, this has been fixed in following releases.

**Comment by nunuhara** [comment]
This should be fixed now. Thanks.
